spring:
  application:
    name: springboot-hibernate-second-cache
  datasource:
    url: jdbc:h2:file:~/demodb
    username: sa
    password: javacompiler
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
  cache:
    type: ehcache

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG